b<-c(10,15,20,25,30,35,40,45,50)
cat('Data B ',b)
a<-c(5,10,15,20,25,30,35,40,45)
cat('Data A',a)
cat('Mean : ', mean(b))
cat('median : ', median(b))
sb<- sort(b)
q1 <- quantile(sb, 0.25, type = 7) # Default method
cat('First Quartile (Q1):', q1, "\n")
q2<-quantile(sb,0.75,type=7)
cat('Third quartile (Q3):',q2,"\n")
cat('Min is',min(sb))
cat('Max is',max(sb))
boxplot(b,main='Boxplot B',col='yellow')
cat('Covariance between A and B: ',cov(a,b))
cat('Corelation between A  and B: ',cor(a,b))
